version: '3.8'
services:
  master:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server

  replica:
    image: redis:latest
    ports:
      - "6380:6380"
    command: redis-server --port 6380 --slaveof master 6379
    depends_on:
      - master
